### ISSUE TITLE
OptiFabric Incompatibility

### ISSUE THREAD

**Issue by kkellogg378** [ToroCraft/ToroHealth#104]
Running the latest version of this mod alongside Optifine via OptiFabric results in all the entities being rendered with shades of blue and pink. Removing either mod from my mods folder fixes the problem. I had previously been running an older version of this mod (fabric 1.17 v5) and it rendered entities in green and red shades.

**Comment by Shakazu** [comment]
After seeing this I tested it out, which fixed the rendering issue from #102 I was having. Just posting a second to this issue (with latest version)
![2021-07-01_23 22 35](https://user-images.githubusercontent.com/86608015/124225684-1de6a780-dac5-11eb-88cf-1b7bb1072795.png)

**Comment by frodare** [comment]
Thanks for letting me know!  I was thinking it was happening when using optifine because I hadn't seen it yet.  Keep an #103 for updates.
