### ISSUE TITLE
1.17.1 [FABRIC] Mod doesn't works

### ISSUE THREAD

**Issue by Nikolass1000** [ToroCraft/ToroHealth#108]
When i installed mod there is nothing that mod should add - bars, particles etc.
config file showed up though
Mods i use:
DarkLoadingScreen 1.6.5
okZoomer 5.0.0 beta 2
Xaeros Minimap 21.13.0
Xaeros Worldmap 1.14.6.1
WTHIT 3.7.0
GeckoLib 3.0.9
FlightHUD for 1.17
Modmenu 2.0.2
Shulkertooltip 3.0.0
Lithium 1.17.1
InventoryHUD 3.3.2
Fabric api 0.37.0
Betterf3 1.15
I will send mod folder here
I didn't edited config file
[mods.zip](https://github.com/ToroCraft/ToroHealth/files/6851736/mods.zip)

**Comment by frodare** [comment]
Please post your config file here too, I remember seeing someone else say it defaulted to all false.

**Comment by Nikolass1000** [comment]
[torohealth.zip](https://github.com/ToroCraft/ToroHealth/files/6851956/torohealth.zip)

**Comment by frodare** [comment]
That looks good.  Does the mod work when it is the only one loaded?

**Comment by NEOLEE98** [comment]
have a similar situation here, but can see particle dmg numbers on mobs

**Comment by frodare** [comment]
I have made a change and released file torohealth-1.17.1-fabric-9.jar.  I didn't have enough time to figure out how to make the mod fail so please post back if it works or not.

**Comment by NEOLEE98** [comment]
Can confirm HUD works with InventoryHUD
InWorld Still doesn't work when iris shader enabled(but still works when shader is off)

**Comment by frodare** [comment]
Thanks for letting me know, I wasn't sure that would fix it :)  I will load that shader later this week and see if I can figure something out with the in world bars.

**Comment by frodare** [comment]
I have another release out, torohealth-1.17.1-fabric-11.jar.  I am hoping that will fix the issue.

**Comment by NEOLEE98** [comment]
Works perfectly, good job!
