### ISSUE TITLE
Very large mobs need scaled

### ISSUE THREAD

**Issue by zeriley** [ToroCraft/ToroHealth#11]
Find a way to determine what scaling each entity needs and scale them appropriately.  Ghasts and the Ender Dragon take up a huge amount of the screen.

Report from Mersid2 on CurseForge:
Also, the mob view panel has position and scaling issues. Mobs like ghasts tend to take up a quarter of my screen. Also, pls make the mob view panel movable separate from the health bar.

**Comment by frodare** [comment]
![2016-12-04_16 15 30](https://cloud.githubusercontent.com/assets/795621/20869275/ea89d0fe-ba3c-11e6-88dc-dbbc807401f3.png)

LOL
