### ISSUE TITLE
3D model not fit to the frame

### ISSUE THREAD

**Issue by Zecka001** [ToroCraft/ToroHealth#111]
1. When scale the HUD the 3D model does not fit to the frame
2. The color of the bar is not right

![toro](https://user-images.githubusercontent.com/87811191/126632961-50073ad8-605d-43e6-87da-bd70e03aae1d.png)

I like this mod, thank you ToroCraft

**Comment by frodare** [comment]
Thanks for reporting this!  I am hoping to fix this issue in the next release.

**Comment by frodare** [comment]
This should be fixed in torohealth-1.17.1-fabric-10.jar
