### ISSUE TITLE
Health bar visible through blocks with shaders 1.17.1

### ISSUE THREAD

**Issue by ApolloTheTwelfth** [ToroCraft/ToroHealth#113]
When inWorld is enabled in any way and at the same time there's Shaders turned on (atleast with all shaders i've used), the health bars(and the left side of some mobs's head, look closely) are visible through blocks. The colors are also different/transparent or not visible at all (i guess depending on which shaders are used).

*Customized as in changed some settings in Shader Options.

I'm also using Vanilla Textures.
![minecraft1](https://user-images.githubusercontent.com/87988938/127013712-79545094-83ac-4957-b8ca-548660afda5c.png)
![minecraft2](https://user-images.githubusercontent.com/87988938/127013717-11ae1221-48dd-4d47-9199-1ce0affe67d8.png)
![minecraft3](https://user-images.githubusercontent.com/87988938/127013720-224d4b23-fa37-4c30-a009-4bf64763b958.png)

**Comment by frodare** [comment]
The larger issues should be fixed now (seeing them through blocks and the face glitch).  However, the in world bars still render poorly when a shader is enabled.  At this time I am not sure how to improve that, but I will continue to look for a solution.
