### ISSUE TITLE
[Curse] [Fabric] Mod requires Fabric API, but it is not mentioned on Curse

### ISSUE THREAD

**Issue by Offenderify** [ToroCraft/ToroHealth#118]
Mod version: 1.17.1-fabric-11
Fabric (Loader) version: 0.11.6
According to fabric.mod.json, this mod requires Fabric API:
```
"depends": {
    "fabricloader": ">=0.7.4",
    "fabric": "*",                              <---------------------
    "minecraft": "1.17.x"
}
```
But this dependency isn't mentioned in the CurseForge description (or in the "Relations" tab).

**Comment by frodare** [comment]
I have never thought to add that in.  I tried updating the file in curse but it doesn't seem to be taking the change.  I will try again later.

**Comment by frodare** [comment]
done
