### ISSUE TITLE
How to keep particles and damage hits number but hide the top-left HUD ?

### ISSUE THREAD

**Issue by Yannoel94** [ToroCraft/ToroHealth#145]
All in the title:
How to keep particles and damage hits number but hide the top-left HUD ?

I would really want to only keep particles and the number of damage on hits,

Thank you so much,

Lunar

**Comment by Andyghandi** [comment]
In the Config, You can disable the HUD elements as following.

    "showEntity": false,
    "showBar": false,
    "showSkin": false

And then set inWorld mode to ALWAYS. (This is the feature where every mob has a bar above them) If you don't wanna have the bar and only the damage particles and numbers, just set the distance to 0.0:

  "inWorld": {
    "mode": "ALWAYS",
    "distance": 0.0,
    "onlyWhenLookingAt": false,
    "onlyWhenHurt": false

That made the trick for me.
