### ISSUE TITLE
Use Villager Profession for Display Name

### ISSUE THREAD

**Issue by frodare** [ToroCraft/ToroHealth#15]
The villager career ID is not sync'ed with the client.  Instead of using `getDisplayName()` for villagers use `getProfessionForge()` and attempt to translate the profession.

Bug reported by Rakarukri:
https://minecraft.curseforge.com/projects/torohealth-damage-indicators?comment=44

**Comment by frodare** [comment]
I could detect if this mod is installed on the server too, and if so figure out a way to send down the missing information.  I would get potion effects that way too, which I would like to see.  I would like to keep this mod where it doesn't require a server side component though.

**Comment by zeriley** [comment]
Our intent is to keep this client-side only.  This will just have to be something we live with.
