### ISSUE TITLE
Incorrect health bar background color

### ISSUE THREAD

**Issue by frodare** [ToroCraft/ToroHealth#16]
[Curse Comment](https://mods.curse.com/mc-mods/minecraft/245733-torohealth-damage-indicators?comment=42) from iPollox

Not entirely sure, but the border layout has turned pink using the 1.11 version (I'm guessing a transparency key?) 

![](http://i.imgur.com/RzQk47x.png)

**Comment by zeriley** [comment]
I bet this is because of the lower-case resource names in 1.11
