### ISSUE TITLE
Add configuration option to only show damage particles if no walls are in the way

### ISSUE THREAD

**Issue by zeriley** [ToroCraft/ToroHealth#17]
Look into a configuration option to accomplish the below

https://minecraft.curseforge.com/projects/torohealth-damage-indicators?comment=48
Comment from clifftrials on CurseForge:
Hello!

Is it normal for damage particles to be showing through floors and walls? I didn't see a config option for direct sight only other than just disabling altogether. Thanks for the mod!

**Comment by frodare** [comment]
This has been fixed in the later versions.
