### ISSUE TITLE
Hostile / Friendly Indicator

### ISSUE THREAD

**Issue by frodare** [ToroCraft/ToroHealth#20]
Dear ToroHealth, thanks for this mod, it's very helpful! But I have little suggestion. Can you add any indication about friendly/hostile mobs is in focus? In modpacks it can sometimes save a life :)
~kostanakis
https://mods.curse.com/mc-mods/minecraft/245733-torohealth-damage-indicators?comment=44

**Comment by zeriley** [comment]
I'm not sure of the best way to accomplish this.  Simplest way would be to add " (Hostile)" at the end of the entity's name, but I'm not a fan of that.  Other idea would be to change the color of the health bar or the entity name (which could be customizable).

**Comment by frodare** [comment]
We could put hostile or friendly on a different line, maybe below name and above the hearts

**Comment by zeriley** [comment]
Would work for the HEARTS display type, but maybe not NUMERIC.  If it takes up any more space, there should definitely be an option to turn it off.

**Comment by frodare** [comment]
added in v10
