### ISSUE TITLE
Crash when looking at AtomicStryker's Minions

### ISSUE THREAD

**Issue by LlubNek** [ToroCraft/ToroHealth#25]
ToroHealth (torohealth-1.11.2-10.jar) crashes when the player looks at a Minion from AtomicStryker's Minions mod in 1.11.2.

Here's the crash report:
[crash-2017-03-05_21.30.43-client.txt](https://github.com/ToroCraft/ToroHealth/files/826180/crash-2017-03-05_21.30.43-client.txt)

**Comment by frodare** [comment]
I'm surprised that has never happened before, looks like it will be an easy fix unless I am missing something, thanks for reporting it!

**Comment by frodare** [comment]
This should be fixed in version 11
