### ISSUE TITLE
Crash report w/ health and info mod, What is causing this ?

### ISSUE THREAD

**Issue by Kylebartaous** [ToroCraft/ToroHealth#27]
Mine craft version: 1.11.2

Forge version w/ lite loader mix in's: 13.20.0.2315

toro health damage indicators version: 1.11.2-11.jar

I seems to be getting a crash with one of the health and info mods , but i am not sure what is doing it.

[crash-2017-06-14_20.03.10-client.txt](https://github.com/ToroCraft/ToroHealth/files/1076326/crash-2017-06-14_20.03.10-client.txt)

The 3-4 mods i use for info on screen and health are, neat, moreoverlays , torohealth damage indictors , jei , wailla, wawla, hwyla. It seems to happen then im looking at a mob and looking down left or down right if it , it would lag for a sec and crash to launcher. thank for you time if you can help me figure what is doing this.

**Comment by frodare** [comment]
Looks like a problem with this mod: ExtraGuiElementMobInfo.  I am out of town for a week, but I will take a closer look at it when I get back.

**Comment by Kylebartaous** [comment]
yep, from talking to another dev seems like its Better Hud doing it

**Comment by zeriley** [comment]
Stacktrace looks like BetterHUD's issue.  Closing this.
