### ISSUE TITLE
(1.12) Every text in-game goes grey 

### ISSUE THREAD

**Issue by conc1erge** [ToroCraft/ToroHealth#28]
When selecting an item ONLY. Selecting an empty hotbar slot will not go grey. Fix?

**Comment by zeriley** [comment]
Can you send a screenshot of this, please?  I haven't been able to reproduce this issue.

**Comment by Guest173661** [comment]
Ok 
![image](https://user-images.githubusercontent.com/29669519/28506788-5ec09e42-7060-11e7-968b-1c734d7c0cb2.png)
