### ISSUE TITLE
[1.12] Unable to turn off health bar

### ISSUE THREAD

**Issue by NillerMedDild** [ToroCraft/ToroHealth#32]
Hey!

I've been unable to turn off the entirety of the 3D animation in the top left corner, that appears when looking at an entity - Is it possible, and if yes, how? Here's my config: https://pastebin.com/RtdcNJC7

I was able to hide it by setting both Y and X to -20000, but I'd rather do it the right way :)

**Comment by frodare** [comment]
This has been fixed in the later versions.
