### ISSUE TITLE
Set the position of the HUD?

### ISSUE THREAD

**Issue by vrackfall** [ToroCraft/ToroHealth#33]
How could I set the position of the HUD via config files or Config GUI?

**Comment by frodare** [comment]
under mod settings, in ToroHealth.  Enjoy!

**Comment by vrackfall** [comment]
This isn't working well on MC 1.12.2.

**Comment by frodare** [comment]
I will look into it, thanks for letting me know.

**Comment by vrackfall** [comment]
And could you add a GUI to edit the HUD position so we can see it on the screen (like it was with Hit-Splat Damage Indicators Mod)

**Comment by frodare** [comment]
I have verified the HUD position config is working as expected on 1.12.2.   I am working on other projects, so I would only be doing bug fixes in here for now.  I recommend creating a new issue requesting that feature, maybe someone will want to work on it.

**Comment by blubbll** [comment]
> I have verified the HUD position config is working as expected on 1.12.2. I am working on other projects, so I would only be doing bug fixes in here for now. I recommend creating a new issue requesting that feature, maybe someone will want to work on it.

not working for me either

**Comment by DoltenBolten** [comment]
It doesn't work on 1.16
