### ISSUE TITLE
Is This Mod Dead?

### ISSUE THREAD

**Issue by Boolyman** [ToroCraft/ToroHealth#34]
The issue with Toro Health constantly spamming damage numbers over Custom NPCs that are not taking damage has been reported for months.  We need a resolution.  And unfortunately this is the only damage number indicator on the market.

**Comment by frodare** [comment]
I wouldn't say this mod is dead, however no one is currently developing it.  I can't say for sure what the issue with Custom NPCs is, but it might not be that easy to fix with the way TH currently detects damage.

One way to fix this issue and a couple others would be to detect when TH is installed on the server too and then take advantage of the additional power. Currently TH is client only.  So if I ever hop back on this project, that would probably be my goal.
