### ISSUE TITLE
[Suggestion] No "damage particles" through walls

### ISSUE THREAD

**Issue by Xiaminou** [ToroCraft/ToroHealth#35]
I don't know if it's possible, but if it is, it would be nice for the "damage particles" to not show up through blocks. For instance, I have a mob farm near my home and I keep seeing the numbers pop up even when I'm not anywhere near it.

**Comment by frodare** [comment]
Seeing damage particles through opaque blocks can be interesting at times, but, yes, overall it seems like a bug.  I know we have looked into this before and it certainly is possible.  Hopefully we can work this into the next release.

**Comment by frodare** [comment]
This issue got fixed in this mod with a config option: https://minecraft.curseforge.com/projects/torohud
