### ISSUE TITLE
Blacklisting/White-listing entities.

### ISSUE THREAD

**Issue by SextupleTap** [ToroCraft/ToroHealth#36]
A section in the config to add entities to be white listed or blacklisted.

Whether it is a black list or a white list could be something like:

//#Set to true to turn this from a blacklist mode to a white-list mode
Whitelist mode: <true/false>

//#List of mobs to be blacklisted/white-listed, to disable players do "player" and to specify any other entity do "modid:entity" e.g "minecraft:zombie"
>
"minecraft:ender_dragon"
"minecraft:wither"
"primitivemobs:lily_lurker"
"examplemod:ghostlyghost"
<

This would be so that the damage indicator will not show specific mob types that are either bosses for example and already have a health bar, or to disable mobs that are supposed to be hidden/hard to see or detect.

**Comment by frodare** [comment]
I like this idea.  Due to the current design of this mod it cannot be enforced by the server, but it still sounds like it would be a nice to have feature.  If get back into MC modding, I will put feature into the next release.

**Comment by SextupleTap** [comment]
Alright, sounds good!

**Comment by frodare** [comment]
This has been implemented in our new mod: https://minecraft.curseforge.com/projects/torohud
