### ISSUE TITLE
Odd miscolored pixels

### ISSUE THREAD

**Issue by UndarkAido** [ToroCraft/ToroHealth#44]
This strange set of Red, Green and Blue pixels appears when I have ToroHealth enabled... It changes as I move my head or walk around.Any ideas as to what is going on?

![image](https://user-images.githubusercontent.com/7421794/77508405-9bd6f000-6e38-11ea-847a-2f3ad4eb2e2e.png)

![image](https://user-images.githubusercontent.com/7421794/77508390-95487880-6e38-11ea-92d3-e5044d5e886d.png)

Edit: Thought it would be prudent to include these: https://gist.github.com/UndarkAido/b4f0e3dc200560579d063cd246b189ff

**Comment by frodare** [comment]
Sorry for the late response. That is strange, but unfortunately I don't know what is going on.  If you can reproduce that issue with only the latest version of ToroHealth installed please feel free to comment back here and I will try to reproduce the issue on my side.
