### ISSUE TITLE
Numbers Dont Pop out of mobs when i hit them

### ISSUE THREAD

**Issue by ShinoAsada** [ToroCraft/ToroHealth#45]
Whenever i try to hit a mob the damage indicators that come off the mob dont show up for some reason. i do have another health mod with it for 1.15 but it shouldnt interfere with it. the numbers for some reason show up. i dont know if its a config thing, i also tried removing the other health mod (orderly) and there is still no change

Config:
https://pastebin.com/AuNe140W

**Comment by ShinoAsada** [comment]
![2020-04-24_09 57 10](https://user-images.githubusercontent.com/49826555/80237768-22d2e000-8612-11ea-9c65-ed2b4b040637.png)

**Comment by frodare** [comment]
I remember correct, I wasn't able to get the damage particles working in 1.15.

**Comment by frodare** [comment]
This has been added back in the latest version.
