### ISSUE TITLE
[Bug/Enhancement] Making damage indicators invisible behind solid blocks.

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [ToroCraft/ToroHealth#50]
This may be a bug but if it's not then it's a request:
Please make damage indicators be invisible if behind solid blocks. Otherwise players can find caves (or players) based off their damage indicators even if the mobs/players aren't in sight.

Using Forge 1.12.2

**Comment by frodare** [comment]
this has been fixed in later versions
