### ISSUE TITLE
Chicken model oversized

### ISSUE THREAD

**Issue by xJon** [ToroCraft/ToroHealth#51]
![Screenshot_1](https://user-images.githubusercontent.com/8945347/90784696-39601e00-e30a-11ea-8fd9-097cb4bcbcf8.png)
Also happens for other modded entities modeled after chickens, like ducks.

**Comment by frodare** [comment]
I have adjusted the scaling of chickens in version 1.16.4-*-4, however supporting other mods is not practical for me.  This mod takes a best guess based on the bound box.
