### ISSUE TITLE
Health bar (in world) rendering above player

### ISSUE THREAD

**Issue by jakey1995abc** [ToroCraft/ToroHealth#53]
The in world Health bar is rendering above my character in first person perspective when using Firstpersonmodel mod.
Minecraft 1.16.2 (Fabric)
ToroHealth Damage Indicators (torohealth-1.16.2-fabric-1.jar)
First-person Model (FirstPersonMod-1.3.0.jar)

**Comment by frodare** [comment]
this has been fixed in later versions
