### ISSUE TITLE
Localization for config.bar.damageNumberType and config.inWorld.mode values

### ISSUE THREAD

**Issue by Golemgator** [ToroCraft/ToroHealth#55]
Could you please add `config.bar.damageNumberType` and `config.inWorld.mode` values to localization file?

`config.bar.damageNumberType`

- NONE
- WHEN_HOLDING_WEAPON
- ALWAYS

`config.inWorld.mode`
- NONE
- LAST
- CUMULATIVE

**Comment by frodare** [comment]
I am no longer supporting in-game config screens in the newer version so this is not longer an issue.  Thanks for your help translating.
