### ISSUE TITLE
fabric 1.16.1 crash when editing 

### ISSUE THREAD

**Issue by Waesh** [ToroCraft/ToroHealth#56]
I have mod menu installed so that I can configure mod settings, and whenever i try to configure my settings for ToroHealth it just crashes. Would like to be able to configure the mod. Thanks

**Comment by frodare** [comment]
I can't promise to get around to it any time soon, but please also attach the crash report with that stack trace.  I believe it is all backed by a json file in the config directory, so you should able to simply edit that with a program like notepad to get you by until it can be fixed.

**Comment by frodare** [comment]
This could have been fixed in the later versions.  Please feel free to comment back here if you are still experiencing this issue in the latest version.
