### ISSUE TITLE
[1.16.3 Fabric] Healthbar Mob Models Broken With Resource Packs

### ISSUE THREAD

**Issue by IdrisQe** [ToroCraft/ToroHealth#58]
When using a resource pack, at least in the Fabric version, which changes mob models, as far as I can tell the healthbar tries to show the vanilla model with the modded texture or something, causing all sorts of visual issues from massively stretched flat planes of texture, to jumbled limbs and half-missing textures. I am, unfortunately, using Optifine and Optifabric, since a lot of the resource pack features don't work without it and have no alternatives.

If this isn't fixable on this mod's end, could there at least be an option to turn off the 3d mob portrait?

**Comment by frodare** [comment]
You can turn off the entity model using `hud.showEntity: false`

This might be fixable on the mod's side.  Could you upload a version of the resource pack here?

**Comment by frodare** [comment]
Assuming this worked as I haven't heard back.
