### ISSUE TITLE
Fabric: No options anymore with 1.16.3-f3

### ISSUE THREAD

**Issue by Meeni-mc** [ToroCraft/ToroHealth#59]
Latest Fabric version removed ModMenu integration. It appears that something else should replace it, but I have not found how to call the configuration menu with the new system. THere's no keybinding, or button, not sure how.??!

**Comment by frodare** [comment]
The config system has been changed out with a unified one as of 1.16.3 version 3 for both Fabric and Forge versions.  The config file can no longer be edited from with-in the game and a text editor such as NotePad must be used. The config file is located at MINECRAFT_FOLDER/config/torohealth.json.  Changes to this file should be reflected in real time if the game is running while the file is edited.  The default file is shown below:

 

{
"watchForChanges": true,
"hud": {
"distance": 60,
"x": 4.0,
"y": 4.0,
"scale": 1.0,
"hideDelay": 20,
"anchorPoint": "TOP_LEFT"
},
"bar": {
"damageNumberType": "LAST",
"friendColor": 16711935,
"friendColorSecondary": 8388863,
"foeColor": -16776961,
"foeColorSecondary": -2147483393
},
"inWorld": {
"mode": "NONE",
"distance": 60.0
}
}
 

 

Values for inWorld.mode
NONE, WHEN_HOLDING_WEAPON, ALWAYS


Values for bar.damageNumberType
NONE, LAST, CUMULATIVE

 
Values for hud.anchorPoint
TOP_LEFT, TOP_CENTER, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_CENTER, BOTTOM_RIGHT

**Comment by Acrivec** [comment]
Update the CurseForge description then. It still says that you can edit it in-game with ModMenu.

**Comment by frodare** [comment]
Ah, I missed a sentence when I added the new section.  It's gone now, thanks!
