### ISSUE TITLE
1.16.3-f3: Optifine (optifabric) in-game life bars are white

### ISSUE THREAD

**Issue by MeeniMc** [ToroCraft/ToroHealth#60]
Since update 1.16.3-fabric 3, there is a new incompatibility with Optifine/optifabric that makes life bars floating above target look "milky". Whatever color these bars are supposed to be, they are rendered in a white-ish, ultra saturated version of it. 

This defect is not present w/o Optifine.

**Comment by frodare** [comment]
Oh strange. I will install optifine and see if I can reproduce it.

**Comment by ajloveslily14** [comment]
I've also noticed it makes entries full bright

**Comment by MeeniMc** [comment]
This is currently (1.18.1) resolved
