### ISSUE TITLE
(1.6.4 Fabric) InWorld bars cause crash when joining world with shaders on

### ISSUE THREAD

**Issue by xdjzack** [ToroCraft/ToroHealth#62]
When i try to enter my world with shaders on, my game crashes, but only when i activate InWorld bars.
If i remove my shaders, then enter the game, and put my shaders back on, then it works.

[Torohealth - InWorld bars cause crash when joining world with shaders on.txt](https://github.com/ToroCraft/ToroHealth/files/5524164/Torohealth.-.InWorld.bars.cause.crash.when.joining.world.with.shaders.on.txt)

**Comment by frodare** [comment]
Interesting. I might not be able to fix the core issue with that, but I should be able to make ToroHealth more bulletproof.  Thanks for taking the time to post this.

**Comment by frodare** [comment]
Looks like I forgot to close this after pushing out the version with the possible fix.  Feel free to comment back here or create a new issue if this is still occurring in the latest version.
