### ISSUE TITLE
Incompatible Datapack(s)

### ISSUE THREAD

**Issue by Coraline77447** [ToroCraft/ToroHealth#64]
Hi. I'm here to report an issue involving datapacks with this mod and why I'm reporting this about it's datapack(s) is cause I'm sick and tired of losing my worlds due to incomplete or missing data within the datapacks or outdated datapacks of some of the mods that I'm playing with which at some point I lose the world that I would be playing on and how I know this is cause when making a new world you can apply datapacks except for datapacks that mods adds, when I look in there I see some red ones that when I hover my mouse over them they say "Incompatible, made for an older version of Minecraft." When I would try to load into a modded world I get a message that says that the selected datapacks have errors and asks me to either enter safe mode (which I can't enter safe mode) or go to title screen and in the message it says that I can manually fix them which Idk how to fix incomplete, missing, outdated, or even broken datapacks to mods that has these errors!!!

**Comment by Meeni-mc** [comment]
Not the author of the mod, but that doesn't seem related to this mod. This mod has no datapack part, and does not do anything with datapacks.

You should obtain a more recent version of the problem datapack. Your problem appears to be that you are running datapacks for a prior version of Minecraft that are not compatible with the version you are now running (e,.g., 1.12 datapack in 1.16 minecraft).

**Comment by frodare** [comment]
@Meeni-mc thanks for chiming in as I don't know anything about the datapack system. 

I did update the version to 6 in the pack.mcmeta file: https://github.com/ToroCraft/ToroHealth/commit/d187c09561b062eaa0dae5fe93a9921b637b6b82#diff-642054513e7de2917f4edb6d7a1b348b9ffc07662df15f7af08bca9b7d849e9dR4 

I will close the issue with that change.
