### ISSUE TITLE
[Bug] 1.16.3 Large custom health quantities cause in-world overhead health bars to skip and repeat offscreen

### ISSUE THREAD

**Issue by PlNG** [ToroCraft/ToroHealth#68]
Custom health quantities cause in-world overhead health bars to skip and repeat offscreen to the right.

I've got some bosses with 200-500 health and their in-world bars are horridly broken. The GUI display is fine.

**Comment by frodare** [comment]
I believe this is caused when an entity is given more health than its max value.  I have patched this so a value greater than 100% will be trimmed to 100%.  That means any mob with greater than max health will have a full health bar until its health gets below whatever its max health is registered as. Hope it helps, enjoy!

**Comment by frodare** [comment]
That is, as of version 1.16.3-*-3
