### ISSUE TITLE
Crush on connection to the server

### ISSUE THREAD

**Issue by Nazguliki** [ToroCraft/ToroHealth#70]
client side:
   **Minecraft 1.16.4**
   **Forge 35.1.3**  
   **torohealth-1.16.4-forge-2.jar**

server side:
   **Forge 35.1.0**
   **torohealth-1.16.4-forge-2.jar**

I have forge server for me and my friend.
The game (not the server) crush on connection to the server. 
[debug.log](https://github.com/ToroCraft/ToroHealth/files/5664539/debug.log)
[latest.log](https://github.com/ToroCraft/ToroHealth/files/5664544/latest.log)

**torohealth.json** settings:
```
{
  "watchForChanges": true,
  "hud": {
    "distance": 60,
    "x": 4.0,
    "y": 4.0,
    "scale": 1.0,
    "hideDelay": 20,
    "anchorPoint": "TOP_CENTER",
    "showEntity": false,
    "showBar": false,
    "showSkin": false
  },
  "bar": {
    "damageNumberType": "CUMULATIVE",
    "friendColor": 16711935,
    "friendColorSecondary": 8388863,
    "foeColor": -16776961,
    "foeColorSecondary": -2147483393
  },
  "inWorld": {
    "mode": "WHEN_HOLDING_WEAPON",
    "distance": 60.0,
    "onlyWhenLookingAt": false,
    "onlyWhenHurt": false
  },
  "particle": {
    "show": true
  }
}
```

**Comment by frodare** [comment]
I think I might know what is going on, will try to fix next time I release a version.

> Notes:
> config is passed in on draw(), meaning it must be called before setEntity().  The call order shouldn't be strict like this

**Comment by frodare** [comment]
I have attempted to fix this issue in This has been add to version 1.16.3-*-3
