### ISSUE TITLE
Crashing when trying to connect to a server

### ISSUE THREAD

**Issue by Blobanium** [ToroCraft/ToroHealth#71]
hi so my game started crashing when i connect to the server most of the time, thankfully i have not enough crashes is installed.

Not enough Crashes Does Catch the crash and identifies it to be torohealth. (proof below)
![Capture](https://user-images.githubusercontent.com/45613796/101710064-a3313e80-3a45-11eb-9fd4-889683333804.PNG)

Crash log
[crash-2020-12-09_17.35.03-client.txt](https://github.com/ToroCraft/ToroHealth/files/5669725/crash-2020-12-09_17.35.03-client.txt)

Mods installed
![Capture](https://user-images.githubusercontent.com/45613796/101710363-2c487580-3a46-11eb-982e-fd817d5ae0e6.PNG)

Im using the fabric version btw

tell me if i need anything else

**Comment by frodare** [comment]
duplicate #70
