### ISSUE TITLE
Life doubled for entities with non-integral HP

### ISSUE THREAD

**Issue by Meeni-mc** [ToroCraft/ToroHealth#72]
Some entities have 26.50 HP (Donkeys, notably). They are shown (incorrectly) as having 53 HP (2x 26.50). 

Screenshot below shows the issue: Hwyla is reporting HP on the top left; ToroHealth in bottom-center. 
![2020-12-12_18 38 50](https://user-images.githubusercontent.com/68366846/102286377-2b13be80-3f06-11eb-9695-d3cf677dea9a.png)

**Comment by frodare** [comment]
Interesting, what mod is the mule from?

**Comment by frodare** [comment]
oh, nevermind, lol

**Comment by frodare** [comment]
I have verified this bug and will have a fix for it in the next release, thanks for letting me know!

**Comment by frodare** [comment]
This should be fixed in version 1.16.4-*-4
