### ISSUE TITLE
Crashes server.

### ISSUE THREAD

**Issue by RDKRACZ** [ToroCraft/ToroHealth#76]
Crash when starting a server with this mod. This mod should be automatically disabled on servers.

**Comment by frodare** [comment]
That should have been fixed, what version are you using?

**Comment by RDKRACZ** [comment]
It's named 1.16.4-fabric-3

**Comment by frodare** [comment]
OK, that makes sense as I did that work on the forge version.  I will look into it and see if I can make it play nice on the server.

**Comment by Acrivec** [comment]
Oh thank you for the info, you could add in the description on that for fabric it's crashing servers (temporarly, until fixed). :)

**Comment by frodare** [comment]
This should have been fixed back on Jan 30, sorry I forgot to post back here.
