### ISSUE TITLE
Mistake in the Config$InWorld.class file

### ISSUE THREAD

**Issue by Asuryan2001** [ToroCraft/ToroHealth#80]
I think there is a mistake in the Config$InWorld.class file because putting ALWAYS after "mode" in "inWorld" in the torohealth.json file doesn't work and in the Config$InWorld.class 2 things are strange : 
    "public ()"    maybe a fonction name is missing
    "public onlyWhenHurt mode"   Is it really "onlyWhenHurt" type ?

(It is possible these issues are not real ones because I don't know the Java language or maybe my java decompiler is bad)

**Comment by frodare** [comment]
This is opensource, so take a look at this and see if it looks better:
https://github.com/ToroCraft/ToroHealth/blob/master/src/main/java/net/torocraft/torohealth/config/Config.java

**Comment by Asuryan2001** [comment]
Yes thanks it is better but I don't find why the ALWAYS mode for InWorld does not work
