### ISSUE TITLE
Add display for potion effects

### ISSUE THREAD

**Issue by zeriley** [ToroCraft/ToroHealth#9]
Request from LaserCatt on CurseForge:
Hello, I would like to give you some advice, I would like to not only show the life bar but also the effects of potions, you could make the symbol of the effect be displayed under the bar life, that would be great. And an extra thing, it would be nice to make the life bar a little more flashy and pretty, because I see it a bit simple for my taste.

**Comment by frodare** [comment]
As far as I can tell, the potion effects information is not updated client side. Since this is a client only mod I am going to close this issue.
