### ISSUE TITLE
Installs Forge version instead of Fabric version with Curseforge App

### ISSUE THREAD

**Issue by vonrix** [ToroCraft/ToroHealth#93]
Even though I selected the fabric version and it displayed the fabric version at time of installing the mod, the Curseforge App downloaded and installed the forge version and when I manually placed the fabric version into the mods folder it then did not know that the fabric version was installed.

I'm not sure how much control you have at having Curseforge App selecting the correct mod platform. Maybe it's more of a Curseforge App bug.

P.S I am using The Curseforge App with the Jumploader mod to use fabric mods with the Cursefoorge App.

Thanks

**Comment by frodare** [comment]
I don't think I really have control over this.  It probably doesn't help that I set fabric as beta so that both versions show on the front page.  I do think curse is working on this issue though.
