### ISSUE TITLE
Maximum distance?

### ISSUE THREAD

**Issue by xJon** [ToroCraft/ToroHealth#96]
Would be nice to have a maximum distance for which the player gets a damage indicator.
E.g. the boar in the screenshot is almost 50 blocks away from the player yet there still is a damage indicator:
![image](https://user-images.githubusercontent.com/8945347/121017531-0c4fff80-c7a6-11eb-8093-e89734ae602d.png)

**Comment by frodare** [comment]
I have added distance key to the particle config. It will be supported in the next 1.17 release. Thanks!

**Comment by xJon** [comment]
> I have added distance key to the particle config. It will be supported in the next 1.17 release. Thanks!

Is the particle rendering distance the same as the indicator entity distance?

**Comment by frodare** [comment]
It defaults to the save of distance 60 blocks, but is a different config value:
`hud.distance` vs `particle.distance`
I am working getting the build out now.

**Comment by frodare** [comment]
File torohealth-1.17-fabric-6.jar is uploading now with the change.  You can add the new config field manually or delete the config file to have a new one generated.  (make sure to back up your config first if have you changes you want to keep)
