### ISSUE TITLE
Damage/heal particles maximum distance

### ISSUE THREAD

**Issue by xJon** [ToroCraft/ToroHealth#97]
Hi,
Similarly to #96, it'd be nice to have a maximum render distance for the damage/healing particles, so players won't see them for mobs that are underground for example:
![image](https://user-images.githubusercontent.com/8945347/121221778-91aedf00-c88e-11eb-8ffd-b768cfc71ebf.png)

**Comment by frodare** [comment]
I have added distance key to the particle config.  It will be supported in the next 1.17 release. Thanks!
